name: Build BunnyX Flashable ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout AK3
      uses: actions/checkout@v4

    - name: Download Kernel Image
      run: |
        git clone --depth=1 --branch BunnyX https://github.com/JOD-BUNNY07/android_kernel_realme_sm7125 kernel
        cp kernel/out/arch/arm64/boot/Image ./Image || true

    - name: Create ZIP
      run: |
        zip -r BunnyX-PERF.zip * -x "*.git*"

    - name: Upload ZIP
      uses: actions/upload-artifact@v4
      with:
        name: BunnyX-PERF
        path: BunnyX-PERF.zip
